
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('gonzalo','admin','ROLE_ADMIN');
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('alejandro','admin','ROLE_ADMIN');
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('maria','admin','ROLE_ADMIN');
 