
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('gonzalo','admin','ROLE_ADMIN');
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('alejandro','admin','ROLE_ADMIN');
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('maria','admin','ROLE_ADMIN');
INSERT INTO MEIT (MEITID,USERNAME,EXPENSE,CONCEPT) VALUES ('1000','gonzalo','25','pagadme');
INSERT INTO MEIT (MEITID,USERNAME,EXPENSE,CONCEPT) VALUES ('1000','gonzalo','Inicial','pagadme');
INSERT INTO USER_DETAIL (USERNAME,EMAIL,DESCRIPTION) VALUES ('gonzalo','g.barceloalvarez@gmail.com','Master');
